/** @format */

/**
 * Base TypeDoc configuration for SSHield packages
 * Generates API documentation in Markdown format compatible with Fuma-docs
 */
interface TypeDocConfig {
	entryPoints?: string[]
	out?: string
	plugin?: string[]
	readme?: string
	includeVersion?: boolean
	categorizeByGroup?: boolean
	defaultCategory?: string
	categoryOrder?: string[]
	sort?: string[]
	exclude?: string[]
	excludePrivate?: boolean
	excludeProtected?: boolean
	excludeInternal?: boolean
	name?: string
	hideGenerator?: boolean
	cleanOutputDir?: boolean
	gitRevision?: string
	sourceLinkTemplate?: string
	basePath?: string
	excludeExternals?: boolean
	excludeNotDocumented?: boolean
	validation?: {
		notExported?: boolean
		invalidLink?: boolean
		notDocumented?: boolean
	}
}

const typedocConfig: TypeDocConfig = {
	// Entry points - should be overridden per package
	entryPoints: ["src/index.ts"],

	// Output directory for generated documentation
	out: "../../docs/content/docs/api",

	// Plugins for markdown generation
	plugin: ["typedoc-plugin-markdown"],

	// README file to include
	readme: "README.md",

	// Include version in documentation
	includeVersion: true,

	// Categorization
	categorizeByGroup: true,
	defaultCategory: "Other",
	categoryOrder: [
		"Classes",
		"Interfaces",
		"Type Aliases",
		"Functions",
		"Variables",
		"*",
	],

	// Sorting
	sort: ["source-order", "required-first", "kind"],

	// Exclude patterns
	exclude: [
		"**/*.spec.ts",
		"**/*.test.ts",
		"**/*.test.tsx",
		"**/node_modules/**",
		"**/dist/**",
	],

	// Visibility filters
	excludePrivate: true,
	excludeProtected: false,
	excludeInternal: true,

	// Hide "Generated by TypeDoc" message
	hideGenerator: true,

	// Clean output directory before generation
	cleanOutputDir: true,

	// Git integration
	gitRevision: "main",

	// Base path for source links
	basePath: ".",

	// Exclude external modules
	excludeExternals: true,

	// Exclude undocumented items
	excludeNotDocumented: false,

	// Validation
	validation: {
		notExported: true,
		invalidLink: true,
		notDocumented: false,
	},
}

export default typedocConfig
